
services:
  app:
    build: .
    container_name: neuro-boost-app
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: neuro-boost-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # Removed port mapping for security - database only accessible internally
    volumes:
      - neuroboost_db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  neuroboost_db_data:

networks:
  app-network:
    driver: bridge
